model:
    combine:
        mlp_hidden_dim: 512

    lora_module:
        inference_mode: False
        r: 8
        lora_alpha: 8
        bias: "lora_only"
        use_rslora: True
        modules_to_save: ['pooler.dense.bias', 'pooler.dense.weight']
        target_modules: ["query", "key", "value"]
        lora_dropout: 0.1

training:
    batch_size: 12
    lr: 0.00001
    train_epochs: 50
