model:
  combine:
    comb_dropout: 0.1
    full_smiles_sequence: true
    lin_proj: false
    mlp_hidden_dim: 512
    no_cross_attn: false
    no_prot_model_ft: true
    single_cross_attn: false
    num_heads: 8
    smiles_hidden_dim: 256
  lora_module:
    bias: none
    inference_mode: false
    lora_alpha: 8
    lora_dropout: 0.1
    modules_to_save:
    - pooler.dense.bias
    - pooler.dense.weight
    r: 8
    target_modules:
    - query
    - key
    - value
    use_rslora: false
  prot_model_card: facebook/esm2_t33_650M_UR50D
  smi_model_card: DeepChem/ChemBERTa-77M-MTR
train_GB:
  max_evals: 500
  use_lorax_embs: false
train_lorax:
  batch_size: 12
  lr: 0.0001
  train_epochs: 50
training:
  data_path: data/CC/scaf_splits
  log_path: logs/CC/scaf_split_no_prot
  results_path: results/CC/scaf_split_no_prot
  binding_sites_path: data/CC/binding_sites/binding_sites.csv
