model:
    smi_model_card: "DeepChem/ChemBERTa-77M-MTR" # NOTE
    prot_model_card: "facebook/esm2_t33_650M_UR50D"
    combine:
        mlp_hidden_dim: 512
        full_smiles_sequence: True
        smiles_hidden_dim: 256
        num_heads: 8
        comb_dropout: 0.1
        no_cross_attn: False
        no_prot_model_ft: True
        lin_proj: False
        single_cross_attn: False

    lora_module:
        inference_mode: False
        r: 8
        lora_alpha: 8
        bias: "none"
        use_rslora: False
        modules_to_save: ["pooler.dense.bias", "pooler.dense.weight"]
        target_modules: ["query", "key", "value"]
        lora_dropout: 0.1

training:
    data_path: "data/M2OR/rand_splits"
    results_path: "results/M2OR/fixed_lora" # NOTE: change for different save folder
    log_path: "logs/M2OR/fixed_lora" # NOTE: change for different save folder

train_lorax:
    batch_size: 21 # NOTE
    lr: 0.0001
    train_epochs: 15 # NOTE

train_GB:
    max_evals: 500
    use_lorax_embs: false # NOTE
